# Generated by Django 2.0.6 on 2018-07-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionParameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('required', models.BooleanField(default=False)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaVantageWrapper.Function')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('regexp_verifier', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='functionparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlphaVantageWrapper.Parameter'),
        ),
    ]
