# Generated by Django 2.0.6 on 2018-06-30 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaVantageWrapper', '0002_auto_20180630_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AlphaVantageWrapper.Parameter'),
        ),
    ]
