# Generated by Django 2.0.6 on 2018-06-30 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlphaVantageWrapper', '0003_auto_20180630_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionparameter',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='AlphaVantageWrapper.Function'),
        ),
    ]
